# fly.toml app configuration file generated for crypto-rates on 2024-11-15T20:38:49-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crypto-rates'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
ENV="FLY"
CSS_FILE="client.css"
JS_FILE="client.mjs"
FIAT_CURRENCIES="USD,AUD,BRL,CAD,CHF,CNY,EUR,GBP,HKD,INR,JPY,KRW,MXN,NZD,RUB,SEK,SGD,TRY"
CRYPTO_LIMIT=25