name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-beam:
    name: Setup BEAM Environment
    runs-on: ubuntu-latest
    steps:
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"

  shared-tests:
    name: Shared Tests
    runs-on: ubuntu-latest
    needs: setup-beam
    steps:
      - uses: actions/checkout@v4
      - name: Run Shared Tests
        run: |
          cd shared
          gleam deps download
          gleam test
          gleam format --check src test

  client-tests:
    name: Client Tests
    runs-on: ubuntu-latest
    needs: shared-tests
    steps:
      - uses: actions/checkout@v4
      - name: Run Client Tests
        run: |
          cd client
          gleam deps download
          gleam test
          gleam format --check src test

  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest
    needs: client-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables from secrets
        run: |
          cd server
          echo "COIN_MARKET_CAP_API_KEY=${{ secrets.COIN_MARKET_CAP_API_KEY }}" >> .env
        shell: bash
      - name: Run Server Tests
        run: |
          cd server
          gleam deps download
          gleam test
          gleam format --check src test