name: Server Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"

      - name: Set environment variables from secrets
        run: |
          echo "COIN_MARKET_CAP_API_KEY=${{ secrets.COIN_MARKET_CAP_API_KEY }}" >> .env
        shell: bash

      - run: gleam deps download
        working-directory: client

      - run: gleam test
        working-directory: client

      - run: gleam format --check src test
        working-directory: client
